### PR TITLE
📝 Add docs for beginners to start

### PR DESCRIPTION
**Pull request by simkimsia**

### CODE REVIEW

**Comment by simkimsia** [comment]
@firdaus let me know if this is okay. I be happy to make changes based on your feedback

**Comment by firdaus** [comment]
This is a good initiative but I don't have the time at the moment to review documentation contributions. 

Would you consider creating a dedicated repo for this documentation and then I can link to it from my repository in case anyone needs some guidance on how to get started.

I do have some plans to write some documentation myself but I think the public API contract isn't stable enough yet to invest in it.

**Comment by simkimsia** [comment]
I don't mind doing it separately 

That would mean I'm the decision maker in that one

**Comment by Irvenae** [comment]
I agree that documentation needs to be added to be able to contribute to this project. Ideally we would also file a proposal to temporal.io.

**Comment by firdaus** [comment]
@Irvenae @simkimsia I have been compiling sample code and publishing it here:
https://onepointzero.app/workflows-in-python-using-temporal/

Let me know if you need any more samples.

**Pull request closed without merging**
